language: android
#wish we had openjdk8, but this will do...
jdk
    - oraclejdk8
android:
  components:

    #wish we had openjdk8, but this will do...putting it here as well
    - oraclejdk8

    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25

